// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP-HVp53NlZqEqdcTVGIwGMQd8bZf5d1Q',
    appId: '1:473018387336:web:af679eb119410353cb883d',
    messagingSenderId: '473018387336',
    projectId: 'myapplication-10-58a1a',
    authDomain: 'myapplication-10-58a1a.firebaseapp.com',
    storageBucket: 'myapplication-10-58a1a.firebasestorage.app',
    measurementId: 'G-LKTNW4N5E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT1jlXJXd_44nrBturPyMMLNkvFycQ5Uk',
    appId: '1:473018387336:android:7f15de1fb9ec3a0fcb883d',
    messagingSenderId: '473018387336',
    projectId: 'myapplication-10-58a1a',
    storageBucket: 'myapplication-10-58a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmESsUK2U3rvlpJ88fi4VoDFIFlmoJbGk',
    appId: '1:473018387336:ios:548011620ea04b53cb883d',
    messagingSenderId: '473018387336',
    projectId: 'myapplication-10-58a1a',
    storageBucket: 'myapplication-10-58a1a.firebasestorage.app',
    iosClientId: '473018387336-o72v53bvtdq3s69bdiuvgdpchj24rs4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.papuaCareerCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmESsUK2U3rvlpJ88fi4VoDFIFlmoJbGk',
    appId: '1:473018387336:ios:548011620ea04b53cb883d',
    messagingSenderId: '473018387336',
    projectId: 'myapplication-10-58a1a',
    storageBucket: 'myapplication-10-58a1a.firebasestorage.app',
    iosClientId: '473018387336-o72v53bvtdq3s69bdiuvgdpchj24rs4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.papuaCareerCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-DjnWnM52Kkk5lU78tbI0R0nYG0JvgKo',
    appId: '1:473018387336:web:0495a931f0a2569dcb883d',
    messagingSenderId: '473018387336',
    projectId: 'myapplication-10-58a1a',
    authDomain: 'myapplication-10-58a1a.firebaseapp.com',
    storageBucket: 'myapplication-10-58a1a.firebasestorage.app',
    measurementId: 'G-HTJFY3ML7M',
  );
}
